name: teste on pull merged

on:
  workflow_run:
    workflows: ["teste on push"]
    branches: [master]
    types:
      - completed

jobs:
  test:
    if: github.event.pull_request.merged == true && ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: echo ${GITHUB_SHA}
